apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-hass.fullname" . }}
  labels:
    {{- include "external-hass.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Values.service.host }}
  ports:
    - port: {{ .Values.service.port }}

  selector:
    {{- include "external-hass.selectorLabels" . | nindent 4 }}
