apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  mytoken.txt: |
    {{ .Values.aliyun.token }}
  myopentoken.txt: |
    {{ .Values.aliyun.opentoken }}
  temp_transfer_folder_id.txt: |
    {{ .Values.aliyun.temp_transfer_folder_id }}