apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "speedtest-tracker.fullname" . }}-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi