apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clash.fullname" . }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "clash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clash.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-proxy
              containerPort: 7890
              protocol: TCP
            - name: socks-proxy
              containerPort: 7891
              protocol: TCP
            - name: admin
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: admin
          # readinessProbe:
          #   exec:
          #     command:
          # TODO: try using http proxy to curl, e.g. https://www.google.com
          #       - 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "/config"
              name: "{{ include "clash.fullname" . }}-pv"
          args: ["-f", "/config/clash.yaml"]
      volumes:
        - name: {{ include "clash.fullname" . }}-pv
          persistentVolumeClaim:
            claimName: {{ include "clash.fullname" . }}-pv-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
