apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clash.fullname" . }}-pv-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi