apiVersion: v1
kind: Service
metadata:
  name: {{ include "clash.fullname" . }}
  labels:
    {{- include "clash.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.service.ipaddress }}

spec:
  type: LoadBalancer
  ports:
    - port: 7890
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy
    - port: 10809
      targetPort: http-proxy
      protocol: TCP
      name: http-proxy-alternative1
    - port: 7891
      targetPort: socks-proxy
      protocol: TCP
      name: socks-proxy
  selector:
    {{- include "clash.selectorLabels" . | nindent 4 }}
