apiVersion: v1
stringData:
  DB_USERNAME: zipline
  DB_DATABASE_NAME: zipline
  DB_PASSWORD: zipline_password
  username: zipline
  password: zipline-password
  CORE_SECRET: VIQz5FRn7T+AdVoKpBaR2fOg3pDHKG15mpIuZ7eY0NU=
kind: Secret
metadata:
  name: zipline-postgres-user
  namespace: zipline
type: kubernetes.io/basic-auth
